{
  "swagger" : "2.0",
  "info" : {
    "description" : "Essa Api versa sobre  o produto MagPY da empresa BEE (Bleeding Edge Enthusiasts) \\n Ela deve armazenar em banco de dados informações dos pacotes necessarios em pythom para rodar um projeto especifico e sua respectiva versão se for apresentada.",
    "version" : "1.0.0",
    "title" : "MagPi",
    "contact" : {
      "email" : "hugobrr@gmail.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host" : "virtserver.swaggerhub.com",
  "basePath" : "/Hugobrr/MagPy/1.0.0",
  "schemes" : [ "https" ],
  "paths" : {
    "/api/projects" : {
      "get" : {
        "tags" : [ "default" ],
        "summary" : "searches inventory",
        "description" : "By passing in the appropriate options, you can search for\navailable inventory in the system\n",
        "operationId" : "searchInventory",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "searchString",
          "in" : "query",
          "description" : "pass an optional search string for looking up inventory",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "skip",
          "in" : "query",
          "description" : "number of records to skip for pagination",
          "required" : false,
          "type" : "integer",
          "minimum" : 0,
          "format" : "int32"
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "maximum number of records to return",
          "required" : false,
          "type" : "integer",
          "maximum" : 50,
          "minimum" : 0,
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Response"
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "post" : {
        "summary" : "Add project with ",
        "description" : "Adds projects in data base",
        "operationId" : "addProjects",
        "consumes" : [ "application/json" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "in" : "body",
          "name" : "name",
          "description" : "Name of projects",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/Request"
          }
        } ],
        "responses" : {
          "201" : {
            "description" : "#/definitions/Response",
            "schema" : {
              "$ref" : "#/definitions/Response"
            }
          },
          "400" : {
            "description" : "error: One or more packages doesn't exist"
          },
          "409" : {
            "description" : "an existing item already exists"
          }
        }
      },
      "delete" : {
        "tags" : [ "default" ],
        "summary" : "searches inventory",
        "description" : "By passing in the appropriate options, you can search for\navailable inventory in the system\n",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "searchString",
          "in" : "query",
          "description" : "pass an optional search string for looking up inventory",
          "required" : false,
          "type" : "string"
        }, {
          "name" : "skip",
          "in" : "query",
          "description" : "number of records to skip for pagination",
          "required" : false,
          "type" : "integer",
          "minimum" : 0,
          "format" : "int32"
        }, {
          "name" : "limit",
          "in" : "query",
          "description" : "maximum number of records to return",
          "required" : false,
          "type" : "integer",
          "maximum" : 50,
          "minimum" : 0,
          "format" : "int32"
        } ],
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Response"
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      }
    }
  },
  "definitions" : {
    "Request" : {
      "type" : "object",
      "required" : [ "name", "packages" ],
      "properties" : {
        "name" : {
          "type" : "string",
          "example" : "titan"
        },
        "packages" : {
          "type" : "array",
          "example" : [ {
            "name" : "Django"
          }, {
            "name" : "graphene",
            "version" : "2.0"
          } ],
          "items" : {
            "type" : "object",
            "properties" : {
              "name" : {
                "type" : "string"
              },
              "version" : {
                "type" : "string"
              }
            },
            "required" : [ "name" ]
          }
        }
      }
    },
    "Response" : {
      "type" : "object",
      "required" : [ "name", "packages" ],
      "properties" : {
        "name" : {
          "type" : "string",
          "example" : "titan"
        },
        "packages" : {
          "type" : "array",
          "example" : [ {
            "name" : "Django",
            "version" : "3.2.5"
          }, {
            "name" : "graphene",
            "version" : "2.0"
          } ],
          "items" : {
            "type" : "object",
            "properties" : {
              "name" : {
                "type" : "string"
              },
              "version" : {
                "type" : "string"
              }
            },
            "required" : [ "name", "version" ]
          }
        }
      }
    }
  }
}